wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668785425.694712
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.13
      5: 0.13.5
      8:
      - 3
      - 5
    visualize:
      my_bar_chart_id:
        panel_config:
          fieldSettings:
            label: Activity
            value: Mean Precision
          panelDefId: wandb/bar/v0
          stringSettings:
            title: PDAN_TSU_RGB Precision on Activities
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: my_bar_chart_id_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
model:
  desc: null
  value: PDAN_TSU_RGB
